import { describe, it, expect } from 'vitest'
import { faker } from '@faker-js/faker'
import * as rules from '../../src/headless/rules'

faker.seed(0xc0ffee)

const N = 50

function times<T>(n: number, fn: (i: number) => T): T[] {
  return Array.from({ length: n }, (_, i) => fn(i))
}

describe('fuzz: email', () => {
  const v = rules.email('Email')
  it(`passes for ${N} faker-generated emails`, () => {
    times(N, () => faker.internet.email()).forEach((e) => {
      expect(v(e), `valid email: ${e}`).toBeUndefined()
    })
  })
  it(`fails for ${N} obviously-invalid strings`, () => {
    const samples = [
      ...times(20, () => faker.lorem.word()),
      ...times(20, () => faker.string.alpha({ length: 10 })),
      ...times(10, () => faker.person.fullName()),
    ]
    samples.forEach((s) => {
      expect(v(s)?.key, `should reject: ${s}`).toBe('email')
    })
  })
})

describe('fuzz: url', () => {
  const v = rules.url('Site')
  it(`passes for ${N} faker-generated http(s) URLs`, () => {
    times(N, () => faker.internet.url({ protocol: faker.helpers.arrayElement(['http', 'https']) }))
      .forEach((u) => {
        expect(v(u), `valid url: ${u}`).toBeUndefined()
      })
  })
  it('fails for malformed strings and disallowed schemes', () => {
    const bad = [
      ...times(20, () => faker.lorem.sentence()),
      ...times(10, () => `ftp://${faker.internet.domainName()}`),
      ...times(10, () => `mailto:${faker.internet.email()}`),
    ]
    bad.forEach((s) => {
      expect(v(s)?.key, `should reject: ${s}`).toBe('url')
    })
  })
})

describe('fuzz: uuid', () => {
  const v = rules.uuid('Id')
  it(`passes for ${N} faker-generated UUIDs`, () => {
    times(N, () => faker.string.uuid()).forEach((id) => {
      expect(v(id), `valid uuid: ${id}`).toBeUndefined()
    })
  })
  it('fails for non-UUID strings', () => {
    const bad = [
      ...times(20, () => faker.string.alphanumeric({ length: 36 })),
      ...times(10, () => faker.string.uuid().slice(0, 35)),
      ...times(10, () => faker.lorem.word()),
    ]
    bad.forEach((s) => {
      expect(v(s)?.key, `should reject: ${s}`).toBe('uuid')
    })
  })
})

describe('fuzz: integer', () => {
  const v = rules.integer('Qty')
  it(`passes for ${N} faker-generated ints (number and stringified)`, () => {
    times(N, (i) => (i % 2 === 0 ? faker.number.int() : String(faker.number.int())))
      .forEach((n) => {
        expect(v(n), `valid int: ${n}`).toBeUndefined()
      })
  })
  it(`fails for ${N} fractional values`, () => {
    times(N, () => faker.number.float({ min: -1000, max: 1000, multipleOf: 0.01 }))
      .filter((n) => !Number.isInteger(n))
      .forEach((n) => {
        expect(v(n)?.key, `should reject: ${n}`).toBe('integer')
      })
  })
})

describe('fuzz: numeric', () => {
  const v = rules.numeric('Amount')
  it('passes for faker numbers and stringified numbers', () => {
    times(N, (i) => (i % 2 === 0 ? faker.number.float() : String(faker.number.float())))
      .forEach((n) => {
        expect(v(n), `valid number: ${n}`).toBeUndefined()
      })
  })
  it('fails for arbitrary words', () => {
    times(N, () => faker.lorem.word()).forEach((w) => {
      // Skip the rare faker word that happens to coerce to a finite number.
      if (Number.isFinite(Number(w))) return
      expect(v(w)?.key, `should reject: ${w}`).toBe('numeric')
    })
  })
})

describe('fuzz: between', () => {
  it('passes for values inside [min,max] generated by faker', () => {
    for (let i = 0; i < N; i++) {
      const min = faker.number.int({ min: -100, max: 100 })
      const max = min + faker.number.int({ min: 1, max: 100 })
      const inside = faker.number.int({ min, max })
      expect(rules.between(min, max)(inside), `${inside} ∈ [${min},${max}]`).toBeUndefined()
    }
  })
  it('fails for values outside [min,max]', () => {
    for (let i = 0; i < N; i++) {
      const min = faker.number.int({ min: 0, max: 100 })
      const max = min + faker.number.int({ min: 1, max: 100 })
      const below = min - faker.number.int({ min: 1, max: 50 })
      const above = max + faker.number.int({ min: 1, max: 50 })
      expect(rules.between(min, max)(below)?.key).toBe('between')
      expect(rules.between(min, max)(above)?.key).toBe('between')
    }
  })
})

describe('fuzz: lengthBetween', () => {
  it('passes for strings inside [min,max] length', () => {
    for (let i = 0; i < N; i++) {
      const min = faker.number.int({ min: 1, max: 10 })
      const max = min + faker.number.int({ min: 0, max: 20 })
      const len = faker.number.int({ min, max })
      const s = faker.string.alphanumeric({ length: len })
      expect(rules.lengthBetween(min, max)(s)).toBeUndefined()
    }
  })
  it('fails for strings outside [min,max] length', () => {
    for (let i = 0; i < N; i++) {
      const min = faker.number.int({ min: 5, max: 10 })
      const max = min + faker.number.int({ min: 1, max: 5 })
      const tooShort = faker.string.alphanumeric({ length: faker.number.int({ min: 1, max: min - 1 }) })
      const tooLong = faker.string.alphanumeric({ length: max + faker.number.int({ min: 1, max: 10 }) })
      expect(rules.lengthBetween(min, max)(tooShort)?.key).toBe('lengthBetween')
      expect(rules.lengthBetween(min, max)(tooLong)?.key).toBe('lengthBetween')
    }
  })
})

describe('fuzz: oneOf', () => {
  it('passes for any allowed value drawn from faker', () => {
    for (let i = 0; i < N; i++) {
      const allowed = times(5, () => faker.lorem.word())
      const pick = faker.helpers.arrayElement(allowed)
      expect(rules.oneOf(allowed)(pick)).toBeUndefined()
    }
  })
  it('fails for values not in the set', () => {
    for (let i = 0; i < N; i++) {
      const allowed = times(5, () => faker.string.uuid())
      const outsider = faker.string.uuid()
      // UUIDs are unique, no collision risk
      expect(rules.oneOf(allowed)(outsider)?.key).toBe('oneOf')
    }
  })
})

describe('fuzz: sameAs', () => {
  it('passes when value equals target', () => {
    times(N, () => faker.string.alphanumeric({ length: 12 })).forEach((s) => {
      expect(rules.sameAs(s)(s)).toBeUndefined()
    })
  })
  it('fails when value differs from target', () => {
    times(N, () => [faker.string.alphanumeric({ length: 12 }), faker.string.alphanumeric({ length: 12 })])
      .forEach(([a, b]) => {
        if (a === b) return // astronomically unlikely, but guard anyway
        expect(rules.sameAs(a)(b)?.key).toBe('sameAs')
      })
  })
})

describe('fuzz: required + uniqueIn under load', () => {
  it('uniqueIn finds collisions in faker-built sibling arrays', () => {
    const siblings = times(20, (i) => ({ sku: `SKU-${i}` }))
    const collisionIdx = faker.number.int({ min: 0, max: 19 })
    const v = rules.uniqueIn(siblings, 999, 'sku')
    expect(v(siblings[collisionIdx]!.sku)?.key).toBe('unique')
    expect(v('NEW-VALUE')).toBeUndefined()
  })
})
